Sleep for a bit when writing to openapi-merged
It is entirely possible to run the next command without finishing writing

```
hbina@akarin ~/g/qdrant (master) [1]> ./tools/generate_openapi_models.sh
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/schema_generator`
[+] Building 2.4s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 31B                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                                              2.1s
 => [1/4] FROM docker.io/library/node:lts-alpine@sha256:f8a51c36b0be7434bbf867d4a08decf0100e656203d893b9b0f8b1fe9e40daea                                                        0.0s
 => [internal] load build context                                                                                                                                               0.0s
 => => transferring context: 162B                                                                                                                                               0.0s
 => CACHED [2/4] WORKDIR /app                                                                                                                                                   0.0s
 => CACHED [3/4] COPY . .                                                                                                                                                       0.0s
 => CACHED [4/4] RUN npm install                                                                                                                                                0.0s
 => exporting to image                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                         0.0s
 => => writing image sha256:28304d6cbac54a2d6e5fb88a1b72bd946331df4db32bb5809ef14178756f7852                                                                                    0.0s
 => => naming to docker.io/library/schema2openapi                                                                                                                               0.0s
No configurations were provided -- using built in recommended configuration by default.

validating openapi-merged.yaml...
Failed to parse api definition at openapi-merged.yaml:

  - can not read an implicit mapping pair; a colon is missed in "/spec/openapi-merged.yaml" (133:9).

/usr/local/lib/node_modules/@redocly/cli/node_modules/@redocly/openapi-core/lib/resolve.js:139
            throw new YamlParseError(e, source);
                  ^

YamlParseError: can not read an implicit mapping pair; a colon is missed in "/spec/openapi-merged.yaml" (133:9)
    at BaseResolver.parseDocument (/usr/local/lib/node_modules/@redocly/cli/node_modules/@redocly/openapi-core/lib/resolve.js:139:19)
    at /usr/local/lib/node_modules/@redocly/cli/node_modules/@redocly/openapi-core/lib/resolve.js:150:29 {
  originalError: YAMLException: can not read an implicit mapping pair; a colon is missed in "/spec/openapi-merged.yaml" (133:9)

   130 |         - cluster
   131 |       summary: Get cluster status info
   132 |       description: Get information abou ...
   133 |       op
  ---------------^
      at generateError (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:183:10)
      at throwError (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:187:9)
      at readBlockMapping (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1136:11)
      at composeNode (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1441:12)
      at readBlockMapping (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1164:11)
      at composeNode (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1441:12)
      at readBlockMapping (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1164:11)
      at composeNode (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1441:12)
      at readBlockMapping (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1164:11)
      at composeNode (/usr/local/lib/node_modules/@redocly/cli/node_modules/js-yaml/lib/loader.js:1441:12) {
    reason: 'can not read an implicit mapping pair; a colon is missed',
    mark: {
      name: '/spec/openapi-merged.yaml',
      buffer: 'paths:\n' +
        '  /telemetry:\n' +
        '    get:\n' +
        '      summary: Collect telemetry data\n' +
        '      description: Collect telemetry data including app info, system info, collections info, cluster info, configs and statistics\n' +
        '      operationId: telemetry\n' +
        '      tags:\n' +
        '        - service\n' +
        '      parameters:\n' +
        '        - name: anonymize\n' +
        '          in: query\n' +
        '          description: If true, anonymize result\n' +
        '          required: false\n' +
        '          schema:\n' +
        '            type: boolean\n' +
        '      responses:\n' +
        '        default:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        4XX:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        "200":\n' +
        '          description: successful operation\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        '                type: object\n' +
        '                properties:\n' +
        '                  time:\n' +
        '                    type: number\n' +
        '                    format: float\n' +
        '                    description: Time spent to process this request\n' +
        '                  status:\n' +
        '                    type: string\n' +
        '                    enum:\n' +
        '                      - ok\n' +
        '                  result:\n' +
        '                    type: array\n' +
        '                    items:\n' +
        "                      $ref: '#/components/schemas/TelemetryData'\n" +
        '  /locks:\n' +
        '    post:\n' +
        '      summary: Set lock options\n' +
        '      description: Set lock options. If write is locked, all write operations and collection creation are forbidden. Returns previous lock options\n' +
        '      operationId: post_locks\n' +
        '      tags:\n' +
        '        - service\n' +
        '      requestBody:\n' +
        '        description: Lock options and optional error message\n' +
        '        content:\n' +
        '          application/json:\n' +
        '            schema:\n' +
        "              $ref: '#/components/schemas/LocksOption'\n" +
        '      responses:\n' +
        '        default:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        4XX:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        "200":\n' +
        '          description: successful operation\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        '                type: object\n' +
        '                properties:\n' +
        '                  time:\n' +
        '                    type: number\n' +
        '                    format: float\n' +
        '                    description: Time spent to process this request\n' +
        '                  status:\n' +
        '                    type: string\n' +
        '                    enum:\n' +
        '                      - ok\n' +
        '                  result:\n' +
        "                    $ref: '#/components/schemas/LocksOption'\n" +
        '    get:\n' +
        '      summary: Get lock options\n' +
        '      description: Get lock options. If write is locked, all write operations and collection creation are forbidden\n' +
        '      operationId: get_locks\n' +
        '      tags:\n' +
        '        - service\n' +
        '      responses:\n' +
        '        default:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        4XX:\n' +
        '          description: error\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        "                $ref: '#/components/schemas/ErrorResponse'\n" +
        '        "200":\n' +
        '          description: successful operation\n' +
        '          content:\n' +
        '            application/json:\n' +
        '              schema:\n' +
        '                type: object\n' +
        '                properties:\n' +
        '                  time:\n' +
        '                    type: number\n' +
        '                    format: float\n' +
        '                    description: Time spent to process this request\n' +
        '                  status:\n' +
        '                    type: string\n' +
        '                    enum:\n' +
        '                      - ok\n' +
        '                  result:\n' +
        "                    $ref: '#/components/schemas/LocksOption'\n" +
        '  /cluster:\n' +
        '    get:\n' +
        '      tags:\n' +
        '        - cluster\n' +
        '      summary: Get cluster status info\n' +
        '      description: Get information about the current state and composition of the cluster\n' +
        '      op\n',
      position: 4096,
      line: 132,
      column: 8,
      snippet: ' 130 |         - cluster\n' +
        ' 131 |       summary: Get cluster status info\n' +
        ' 132 |       description: Get information abou ...\n' +
        ' 133 |       op\n' +
        '---------------^'
    }
  },
  source: Source {
    absoluteRef: '/spec/openapi-merged.yaml',
    body: 'paths:\n' +
      '  /telemetry:\n' +
      '    get:\n' +
      '      summary: Collect telemetry data\n' +
      '      description: Collect telemetry data including app info, system info, collections info, cluster info, configs and statistics\n' +
      '      operationId: telemetry\n' +
      '      tags:\n' +
      '        - service\n' +
      '      parameters:\n' +
      '        - name: anonymize\n' +
      '          in: query\n' +
      '          description: If true, anonymize result\n' +
      '          required: false\n' +
      '          schema:\n' +
      '            type: boolean\n' +
      '      responses:\n' +
      '        default:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        4XX:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        "200":\n' +
      '          description: successful operation\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      '                type: object\n' +
      '                properties:\n' +
      '                  time:\n' +
      '                    type: number\n' +
      '                    format: float\n' +
      '                    description: Time spent to process this request\n' +
      '                  status:\n' +
      '                    type: string\n' +
      '                    enum:\n' +
      '                      - ok\n' +
      '                  result:\n' +
      '                    type: array\n' +
      '                    items:\n' +
      "                      $ref: '#/components/schemas/TelemetryData'\n" +
      '  /locks:\n' +
      '    post:\n' +
      '      summary: Set lock options\n' +
      '      description: Set lock options. If write is locked, all write operations and collection creation are forbidden. Returns previous lock options\n' +
      '      operationId: post_locks\n' +
      '      tags:\n' +
      '        - service\n' +
      '      requestBody:\n' +
      '        description: Lock options and optional error message\n' +
      '        content:\n' +
      '          application/json:\n' +
      '            schema:\n' +
      "              $ref: '#/components/schemas/LocksOption'\n" +
      '      responses:\n' +
      '        default:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        4XX:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        "200":\n' +
      '          description: successful operation\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      '                type: object\n' +
      '                properties:\n' +
      '                  time:\n' +
      '                    type: number\n' +
      '                    format: float\n' +
      '                    description: Time spent to process this request\n' +
      '                  status:\n' +
      '                    type: string\n' +
      '                    enum:\n' +
      '                      - ok\n' +
      '                  result:\n' +
      "                    $ref: '#/components/schemas/LocksOption'\n" +
      '    get:\n' +
      '      summary: Get lock options\n' +
      '      description: Get lock options. If write is locked, all write operations and collection creation are forbidden\n' +
      '      operationId: get_locks\n' +
      '      tags:\n' +
      '        - service\n' +
      '      responses:\n' +
      '        default:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        4XX:\n' +
      '          description: error\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      "                $ref: '#/components/schemas/ErrorResponse'\n" +
      '        "200":\n' +
      '          description: successful operation\n' +
      '          content:\n' +
      '            application/json:\n' +
      '              schema:\n' +
      '                type: object\n' +
      '                properties:\n' +
      '                  time:\n' +
      '                    type: number\n' +
      '                    format: float\n' +
      '                    description: Time spent to process this request\n' +
      '                  status:\n' +
      '                    type: string\n' +
      '                    enum:\n' +
      '                      - ok\n' +
      '                  result:\n' +
      "                    $ref: '#/components/schemas/LocksOption'\n" +
      '  /cluster:\n' +
      '    get:\n' +
      '      tags:\n' +
      '        - cluster\n' +
      '      summary: Get cluster status info\n' +
      '      description: Get information about the current state and composition of the cluster\n' +
      '      op',
    mimeType: undefined
  },
  line: 133,
  col: 9
}

Node.js v19.1.0
```

I suspect 5 seconds is a bit too high and there's probably more places where this need to happen?

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>